apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphical-auth-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphical-auth
  template:
    metadata:
      labels:
        app: graphical-auth
    spec:
      containers:
      - name: graphical-auth
        image: charan1926/graphical-auth:latest
        ports:
        - containerPort: 8000
