apiVersion: v1
kind: Service
metadata:
  name: graphical-auth-service
  namespace: default
spec:
  selector:
    app: graphical-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
