apiVersion: v1
kind: Service
metadata:
  name: graphical-auth-service
spec:
  selector:
    app: graphical-password-auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort
